USE [dbname]
GO;

CREATE TABLE Customers 
(
	Id NVARCHAR2(5) NOT NULL,
	Name NVARCHAR2(30) NOT NULL,
	Address NVARCHAR2(60) NULL,
	City NVARCHAR2(15) NULL,
	Country NVARCHAR2(15) NULL,
	PostalCode NVARCHAR2(10) NULL,
	Phone NVARCHAR2(24) NULL,
	PRIMARY KEY (Id)
);